#!/bin/bash
# delete profile from a given device by UDID
# Example:
#          ./tools/delete_profile $udid $payload_identifier
#
source $NANODIRECTOR_ENV_PATH
endpoint="profile"
jq -n \
  --arg udid "$1" \
  --arg payload_identifier "$2" \
  '.udids = [$udid]
  |.profiles[0].payload_identifier = $payload_identifier
  |.metadata = true
  |.push_now = true
  '|\
  curl -u "nanodirector:$API_TOKEN" -X DELETE "$SERVER_URL/$endpoint" -d@-
