on: release
name: Handle Release
jobs:
  upload:
    name: Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Upload
        uses: ./.github/actions/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "nanodirector-linux nanodirector-darwin"
